### ISSUE TITLE
overflow hidden

### ISSUE THREAD

**Issue by Haroenv** [algolia/marvel-search#4]
There's `overflow: hidden` on the body, but that prevents scrolling altogether. That means you can't access all of the filters.

**Comment by pixelastic** [comment]
Hmm, I've added `overflow-y: auto;` on the sidebar and main content, that should let you scroll them independently. What browser are you using?

**Comment by Haroenv** [comment]
Safari, and on line `120` of the compiled css there's a rule:

```css
html, body {
    margin: 0;
    height: 100%;
    overflow: hidden
}
```

**Comment by pixelastic** [comment]
You should also have a few lines later:
```css
.l-sidebar {
    display: none;
    overflow-y: auto
}
```

I don't have a Safari to test on... @LukyVj do you have a Safari and can you replicate the issue?
